export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST'

export const USER_AUTHENTICATED_BY_TOKEN_FOUND = "USER_AUTHENTICATED_BY_TOKEN_FOUND"
export const PUT_PARAMETRIZACAO_CLIENTE_FROM_TOKEN = "PUT_PARAMETRIZACAO_CLIENTE_FROM_TOKEN"

export const ERROR_USER_MESSAGE = 'ERROR_USER_MESSAGE'

