export const EMPTY_DATA_ALL_RESOURCES = 'EMPTY_DATA_ALL_RESOURCES'

export const GENERIC_ERROR_MSG = 'GENERIC_ERROR_MSG'
export const SET_GENERIC_MSG = 'SET_GENERIC_MSG'

export const GET_RESOURCE_BY_ID_REQUEST = 'GET_RESOURCE_BY_ID_REQUEST'
export const GET_RESOURCE_BY_ID_SUCCESS = 'GET_RESOURCE_BY_ID_SUCCESS'

export const CREATE_RESOURCE_REQUEST = 'CREATE_RESOURCE_REQUEST'
export const CREATE_RESOURCE_ERROR = 'CREATE_RESOURCE_ERROR'

export const UPDATE_RESOURCE_REQUEST = 'UPDATE_RESOURCE_REQUEST'
export const UPDATE_RESOURCE_SUCCESS = 'UPDATE_RESOURCE_SUCCESS'

export const RESOURCE_SELECTED = 'RESOURCE_SELECTED'

export const DELETE_RESOURCE_REQUEST = 'DELETE_RESOURCE_REQUEST'

export const SET_SUCCESS = 'SET_SUCCESS'

export const GET_TO_COLLECTION_REQUEST = 'GET_TO_COLLECTION_REQUEST'
export const GET_TO_COLLECTION_SUCCESS = 'GET_TO_COLLECTION_SUCCESS'

export const SET_FETCHING_DATA_FALSE = 'SET_FETCHING_DATA_FALSE'

export const PUT_OBJECT_IN_STATE = 'PUT_OBJECT_IN_STATE'
export const REMOVE_OBJECT_FROM_STATE = 'REMOVE_OBJECT_FROM_STATE'

export const MESSAGE_SUCCESS = 'MESSAGE_SUCCESS'